/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmvMasterRouteImport } from './routes/smv-master'
import { Route as SewingPlanUploadRouteImport } from './routes/sewing-plan-upload'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductionPlanRouteImport } from './routes/production-plan'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BuildupRouteImport } from './routes/buildup'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LineCapacityIndexRouteImport } from './routes/line-capacity.index'
import { Route as LineCapacityLineIdRouteImport } from './routes/line-capacity.$lineId'

const SmvMasterRoute = SmvMasterRouteImport.update({
  id: '/smv-master',
  path: '/smv-master',
  getParentRoute: () => rootRouteImport,
} as any)
const SewingPlanUploadRoute = SewingPlanUploadRouteImport.update({
  id: '/sewing-plan-upload',
  path: '/sewing-plan-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionPlanRoute = ProductionPlanRouteImport.update({
  id: '/production-plan',
  path: '/production-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildupRoute = BuildupRouteImport.update({
  id: '/buildup',
  path: '/buildup',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LineCapacityIndexRoute = LineCapacityIndexRouteImport.update({
  id: '/line-capacity/',
  path: '/line-capacity/',
  getParentRoute: () => rootRouteImport,
} as any)
const LineCapacityLineIdRoute = LineCapacityLineIdRouteImport.update({
  id: '/line-capacity/$lineId',
  path: '/line-capacity/$lineId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/buildup': typeof BuildupRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/plan': typeof PlanRoute
  '/planning': typeof PlanningRoute
  '/production-plan': typeof ProductionPlanRoute
  '/reports': typeof ReportsRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/sewing-plan-upload': typeof SewingPlanUploadRoute
  '/smv-master': typeof SmvMasterRoute
  '/line-capacity/$lineId': typeof LineCapacityLineIdRoute
  '/line-capacity/': typeof LineCapacityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/buildup': typeof BuildupRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/plan': typeof PlanRoute
  '/planning': typeof PlanningRoute
  '/production-plan': typeof ProductionPlanRoute
  '/reports': typeof ReportsRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/sewing-plan-upload': typeof SewingPlanUploadRoute
  '/smv-master': typeof SmvMasterRoute
  '/line-capacity/$lineId': typeof LineCapacityLineIdRoute
  '/line-capacity': typeof LineCapacityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/buildup': typeof BuildupRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/plan': typeof PlanRoute
  '/planning': typeof PlanningRoute
  '/production-plan': typeof ProductionPlanRoute
  '/reports': typeof ReportsRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/sewing-plan-upload': typeof SewingPlanUploadRoute
  '/smv-master': typeof SmvMasterRoute
  '/line-capacity/$lineId': typeof LineCapacityLineIdRoute
  '/line-capacity/': typeof LineCapacityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/buildup'
    | '/calendar'
    | '/dashboard'
    | '/import'
    | '/plan'
    | '/planning'
    | '/production-plan'
    | '/reports'
    | '/scenarios'
    | '/settings'
    | '/sewing-plan-upload'
    | '/smv-master'
    | '/line-capacity/$lineId'
    | '/line-capacity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/buildup'
    | '/calendar'
    | '/dashboard'
    | '/import'
    | '/plan'
    | '/planning'
    | '/production-plan'
    | '/reports'
    | '/scenarios'
    | '/settings'
    | '/sewing-plan-upload'
    | '/smv-master'
    | '/line-capacity/$lineId'
    | '/line-capacity'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/buildup'
    | '/calendar'
    | '/dashboard'
    | '/import'
    | '/plan'
    | '/planning'
    | '/production-plan'
    | '/reports'
    | '/scenarios'
    | '/settings'
    | '/sewing-plan-upload'
    | '/smv-master'
    | '/line-capacity/$lineId'
    | '/line-capacity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  BuildupRoute: typeof BuildupRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  ImportRoute: typeof ImportRoute
  PlanRoute: typeof PlanRoute
  PlanningRoute: typeof PlanningRoute
  ProductionPlanRoute: typeof ProductionPlanRoute
  ReportsRoute: typeof ReportsRoute
  ScenariosRoute: typeof ScenariosRoute
  SettingsRoute: typeof SettingsRoute
  SewingPlanUploadRoute: typeof SewingPlanUploadRoute
  SmvMasterRoute: typeof SmvMasterRoute
  LineCapacityLineIdRoute: typeof LineCapacityLineIdRoute
  LineCapacityIndexRoute: typeof LineCapacityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smv-master': {
      id: '/smv-master'
      path: '/smv-master'
      fullPath: '/smv-master'
      preLoaderRoute: typeof SmvMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sewing-plan-upload': {
      id: '/sewing-plan-upload'
      path: '/sewing-plan-upload'
      fullPath: '/sewing-plan-upload'
      preLoaderRoute: typeof SewingPlanUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-plan': {
      id: '/production-plan'
      path: '/production-plan'
      fullPath: '/production-plan'
      preLoaderRoute: typeof ProductionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildup': {
      id: '/buildup'
      path: '/buildup'
      fullPath: '/buildup'
      preLoaderRoute: typeof BuildupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line-capacity/': {
      id: '/line-capacity/'
      path: '/line-capacity'
      fullPath: '/line-capacity/'
      preLoaderRoute: typeof LineCapacityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line-capacity/$lineId': {
      id: '/line-capacity/$lineId'
      path: '/line-capacity/$lineId'
      fullPath: '/line-capacity/$lineId'
      preLoaderRoute: typeof LineCapacityLineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  BuildupRoute: BuildupRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  ImportRoute: ImportRoute,
  PlanRoute: PlanRoute,
  PlanningRoute: PlanningRoute,
  ProductionPlanRoute: ProductionPlanRoute,
  ReportsRoute: ReportsRoute,
  ScenariosRoute: ScenariosRoute,
  SettingsRoute: SettingsRoute,
  SewingPlanUploadRoute: SewingPlanUploadRoute,
  SmvMasterRoute: SmvMasterRoute,
  LineCapacityLineIdRoute: LineCapacityLineIdRoute,
  LineCapacityIndexRoute: LineCapacityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
